
version: 0.0.{build}
install:
  # Use the install script to grab the latest dotnet install
  - ps: iex .\dotnet-latest.ps1
  - choco install gitversion.portable -pre -y
  # Prepend newly installed dotnet cli to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=C:\\Program Files\\dotnet\\bin;%PATH%"  

before_build:
  - cmd: dotnet --version
  - ps: gitversion /l console /output buildserver


build_script:
  - cmd: build.cmd
  - cmd: tests\CodeCoverage\CodeCoverage.cmd

after_build:
  - cmd: appveyor PushArtifact "artifacts\SixLabors.Shapes.%GitVersion_NuGetVersion%.nupkg"

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/sixlabors/api/v2/package
    symbol_server: https://www.myget.org/F/sixlabors/symbols/api/v2/package
    api_key:
      secure: SyrSERGrjkK21TSCsHtqke5279SMxXCg2NXKjR2qaErP0khEplwxPwE8Ch5bxzyf
    artifact: /.*\.nupkg/
    on:
      branch: master

test: off